# -*- coding: utf-8 -*-
"""「Linear Algebra - hw3」的副本

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jDBVpMz3a7r89xLL1w8nTwn08QR592Iw
"""

import numpy as np
import matplotlib.image as img
import matplotlib.pyplot as plt
import math

# Mount your google drive to save your gif result.
from google.colab import drive
drive.mount('/content/drive')

# For question (4)
# you cannot use x to compute the center and the radius inside this function.
'''def dataSampling(x):
    ret = []
    num = 0
    for i in x :
      if num % 25 == 0 :
        ret.append(i)
      num += 1
    return ret'''
def dataSampling(x):
    ret = []
    for i in x :
      flag = 1
      for j in ret :
        # 60*60 circle area
        if (i[0] - j[0]) * (i[0] - j[0]) + (i[1] - j[1]) * (i[1] - j[1]) < 3600 : 
          flag = 0
          break
      if(flag) :
        ret.append(i)

    return ret

def circle(sp) :
    n=len(sp)
    A = np.zeros((n, 3))
    b = np.zeros((n))
    for i in range(n):
        pt = sp[i]
        A[i, :] = [2.*pt[0], 2.*pt[1], 1]
        b[i] = pt[0]*pt[0]+pt[1]*pt[1]
    return A, b

def draw_circle(x, h, w) :
    center = [x[0], x[1]]
    radius = math.sqrt(x[2]+x[0]*x[0]+x[1]*x[1])

    x_axis = np.linspace(0, w, 700)
    y_axis = np.linspace(0, h, 700)

    a, b = np.meshgrid(x_axis, y_axis)

    C = (a - x[0])*(a - x[0]) + (b - x[1])*(b - x[1]) - radius*radius
    return a, b, C

#----------Q3----------#
def ellipse(sp) :
    n=len(sp)
    # TODO: How many variable should use?
    A = np.zeros((n, 5))
    b = np.ones((n))
    for i in range(n):
        pt = sp[i]
        x = pt[0]
        y = pt[1]
        # TODO: ellipse formula here.
        A[i, :] = [1.*x*x, 1.*x*y, 1.*y*y, 1.*x, 1.*y]
        b[i] = 1.

    return A, b

def draw_ellipse(x, h, w) :
    # plot the drawing and the fitted circle
    x_axis = np.linspace(0, w, 700)
    y_axis = np.linspace(0, h, 700)

    a, b = np.meshgrid(x_axis, y_axis)

    # TODO: ellipse formula here.
    C = x[0]*a*a + x[1]*a*b + x[2]*b*b + x[3]*a + x[4]*b - 1.

    return a, b, C

"""# DO NOT MODIFY THE JUDGE CODE!!!"""

def judge_overlapping(points) :
    # calculate all sample point circle.
    A, b = circle(points)
    sol1 = np.linalg.lstsq(A, b, rcond=None)[0]
    x1 = sol1[0]
    y1 = sol1[1]
    r1 = math.sqrt(sol1[2]+x1**2+y1**2)

    sp = dataSampling(points)
    A, b = circle(sp)
    sol2 = np.linalg.lstsq(A, b, rcond=None)[0]
    x2 = sol2[0]
    y2 = sol2[1]
    r2 = math.sqrt(sol2[2]+x2**2+y2**2)

    d = math.sqrt((x1-x2)**2 + (y1-y2)**2)

    if r1+r2 <= d :
        # 1 point or no point
        return 0
    elif min(r1, r2) + d <= max(r1, r2) :
        # inner circle
        return (min(r1, r2)**2) / (max(r1, r2)**2)
   
    alpha = math.acos((r1**2 + d**2 - r2**2) / (2 * r1 * d))
    beta = math.acos((r2**2 + d**2 - r1**2) / (2 * r2 * d))

    overlapping = alpha * (r1**2) + beta * (r2**2) - (r1**2) * math.cos(alpha) * math.sin(alpha) - (r2**2) * math.cos(beta) * math.sin(beta)

    return overlapping / (max(r1**2, r2**2) * np.pi)

def judge_sampling(points) :
    old_points = list(points)
    all_point = len(points)
    sp = dataSampling(points)
    sp_len = 0
    for p in sp :
        for ss in old_points :
            if ss[0] == p[0] and ss[1] == p[1] :
                sp_len += 1
    
    if (old_points != points) :
        return 0

    return (all_point - sp_len) / all_point


def judge(points) :
    sample = judge_sampling(points)
    overlap = judge_overlapping(points)

    print("The score of this question is : ")
    print("20 * (0.3 * ? (Efficiency, need your report) + 0.3 * {:f} (correctness) + 0.4 * {:f} (sampling) ) =  ? + {:f}".format(overlap, sample, 20 * (0.3 * overlap + 0.4 * sample)))

def main(file, mode="circle") :
    # read image and get circle points
    #im1 = img.imread('puddle.png')
    im1 = img.imread(file)
    [h, w, c] = np.array(im1).shape
    points = [];
    for i in range(h):
        for j in range(w):
            if (all(im1[i,j,:])==0):
                points.append([i, j])


    # sampling data
    sp = dataSampling(points)

    if mode == "circle":
        # create matrix for fitting
        A, b = circle(sp)

        # solve the least square problem
        #[x, residual, rank] = np.linalg.lstsq(A, b, rcond=None)[0:3]
        #print(rank)

        #----------Q2----------#
        # normal equation method. A^T*Ax=A^T*b -> x = (A^T*A)^-1*(A^T*b)
        x = np.dot(np.linalg.inv(np.dot(A.T, A)), np.dot(A.T, b))
        e = b - np.dot(A, x) #error(residual)
        e = np.dot(e, e) #squared
        #print(e)

        a, b, C = draw_circle(x, h, w)
    elif mode == "ellipse":
        # create matrix for fitting
        A, b = ellipse(sp)

        # solve the least square problem
        [x, r, rank] = np.linalg.lstsq(A, b, rcond=None)[0:3]

        a, b, C = draw_ellipse(x, h, w)

    figure, axes = plt.subplots(1)
    plt.imshow(im1) 
    axes.contour(b, a, C, [0])
    axes.set_aspect(1)
    plt.savefig(file+'.output.png')
    plt.show()
    points = [];
    for i in range(h):
        for j in range(w):
            if (all(im1[i,j,:])==0):
                points.append([i, j])
    judge(points)
    print("="*50)

#files = ['case1.png', 'case2.png', 'case3.png', '2(c).png']
files = ['case1.png', 'case2.png', 'case3.png', 'case4.png', 'case5.png']
for f in files :
    main('/content/drive/My Drive/hw3/' + f, mode="circle")
    #main('/content/drive/My Drive/hw3/' + f, mode="ellipse")
#main('/content/drive/My Drive/hw3/case1.png', mode="circle")
#main('/content/drive/My Drive/eclipse.png', mode="ellipse")